{
  "hash": "a38062efd80b7f07772ffe6a62932488",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Dr. Semmelweis and the Discovery of Handwashing\"\nformat:\n  html:\n    code-fold: true\nexecute:\n  echo: true\nauthor: \"Hamza Rahal\"\ndate: \"2024-07-09\"\ncategories: [project, code, analysis]\n---\n\n\n## 1. Meet Dr. Ignaz Semmelweis\n\nThis is Dr. Ignaz Semmelweis, a Hungarian physician born in 1818 and active at the Vienna General Hospital. If Dr. Semmelweis looks troubled it's probably because he's thinking about *childbed fever*: A deadly disease affecting women that just have given birth. He is thinking about it because in the early 1840s at the Vienna General Hospital as many as 10% of the women giving birth die from it. He is thinking about it because he knows the cause of childbed fever: It's the contaminated hands of the doctors delivering the babies. And they won't listen to him and *wash their hands*!\n\nIn this notebook, we're going to reanalyze the data that made Semmelweis discover the importance of *handwashing*. Let's start by looking at the data that made Semmelweis realize that something was wrong with the procedures at Vienna General Hospital.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in the tidyverse package\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\n# Read datasets/yearly_deaths_by_clinic.csv into yearly\nyearly <- read_csv(\"yearly_deaths_by_clinic.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 12 Columns: 4\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): clinic\ndbl (3): year, births, deaths\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Print out yearly\nyearly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n    year births deaths clinic  \n   <dbl>  <dbl>  <dbl> <chr>   \n 1  1841   3036    237 clinic 1\n 2  1842   3287    518 clinic 1\n 3  1843   3060    274 clinic 1\n 4  1844   3157    260 clinic 1\n 5  1845   3492    241 clinic 1\n 6  1846   4010    459 clinic 1\n 7  1841   2442     86 clinic 2\n 8  1842   2659    202 clinic 2\n 9  1843   2739    164 clinic 2\n10  1844   2956     68 clinic 2\n11  1845   3241     66 clinic 2\n12  1846   3754    105 clinic 2\n```\n\n\n:::\n:::\n\n\n## 2. The alarming number of deaths\n\nThe table above shows the number of women giving birth at the two clinics at the Vienna General Hospital for the years 1841 to 1846. You'll notice that giving birth was very dangerous; an *alarming* number of women died as the result of childbirth, most of them from childbed fever.\n\nWe see this more clearly if we look at the *proportion of deaths* out of the number of women giving birth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Adding a new column to yearly with proportion of deaths per no. births\nyearly <- yearly  %>% mutate(proportion_deaths = deaths/births)\n\n# Print out yearly\nyearly\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 5\n    year births deaths clinic   proportion_deaths\n   <dbl>  <dbl>  <dbl> <chr>                <dbl>\n 1  1841   3036    237 clinic 1            0.0781\n 2  1842   3287    518 clinic 1            0.158 \n 3  1843   3060    274 clinic 1            0.0895\n 4  1844   3157    260 clinic 1            0.0824\n 5  1845   3492    241 clinic 1            0.0690\n 6  1846   4010    459 clinic 1            0.114 \n 7  1841   2442     86 clinic 2            0.0352\n 8  1842   2659    202 clinic 2            0.0760\n 9  1843   2739    164 clinic 2            0.0599\n10  1844   2956     68 clinic 2            0.0230\n11  1845   3241     66 clinic 2            0.0204\n12  1846   3754    105 clinic 2            0.0280\n```\n\n\n:::\n:::\n\n\n## 3. Death at the clinics\n\nIf we now plot the proportion of deaths at both clinic 1 and clinic 2 we'll see a curious pattern...\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Setting the size of plots in this notebook\noptions(repr.plot.width = 7, repr.plot.height = 4)\n\n# Plot yearly proportion of deaths at the two clinics\nggplot(yearly, aes(x = year, y = proportion_deaths, col = clinic)) + \n  geom_line()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## 4. The handwashing begins\n\nWhy is the proportion of deaths constantly so much higher in Clinic 1? Semmelweis saw the same pattern and was puzzled and distressed. The only difference between the clinics was that many medical students served at Clinic 1, while mostly midwife students served at Clinic 2. While the midwives only tended to the women giving birth, the medical students also spent time in the autopsy rooms examining corpses.\n\nSemmelweis started to suspect that something on the corpses, spread from the hands of the medical students, caused childbed fever. So in a desperate attempt to stop the high mortality rates, he decreed: *Wash your hands!* This was an unorthodox and controversial request, nobody in Vienna knew about bacteria at this point in time.\n\nLet's load in monthly data from Clinic 1 to see if the handwashing had any effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read datasets/monthly_deaths.csv into monthly\nmonthly <- read_csv(\"monthly_deaths.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 98 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl  (2): births, deaths\ndate (1): date\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Adding a new column with proportion of deaths per no. births\nmonthly <- monthly  %>% mutate(proportion_deaths = deaths/births)\n\n# Print out the first rows in monthly\nhead(monthly)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  date       births deaths proportion_deaths\n  <date>      <dbl>  <dbl>             <dbl>\n1 1841-01-01    254     37           0.146  \n2 1841-02-01    239     18           0.0753 \n3 1841-03-01    277     12           0.0433 \n4 1841-04-01    255      4           0.0157 \n5 1841-05-01    255      2           0.00784\n6 1841-06-01    200     10           0.05   \n```\n\n\n:::\n:::\n\n\n## 5. The effect of handwashing\n\nWith the data loaded we can now look at the proportion of deaths over time. In the plot below we haven't marked where obligatory handwashing started, but it reduced the proportion of deaths to such a degree that you should be able to spot it!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(monthly, aes(date, proportion_deaths)) +\n  geom_line() +\n  labs(x = \"Year\", y = \"Proportion Deaths\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## 6. The effect of handwashing highlighted\n\nStarting from the summer of 1847 the proportion of deaths is drastically reduced and, yes, this was when Semmelweis made handwashing obligatory.\n\nThe effect of handwashing is made even more clear if we highlight this in the graph.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# From this date handwashing was made mandatory\nhandwashing_start = as.Date('1847-06-01')\n\n# Add a TRUE/FALSE to monthly called handwashing_started\nmonthly <- monthly %>%\n  mutate(handwashing_started = date >= handwashing_start)\n\n# Plot monthly proportion of deaths before and after handwashing\nggplot(monthly, aes(x = date, y = proportion_deaths, color = handwashing_started)) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n## 7. More handwashing, fewer deaths?\n\nAgain, the graph shows that handwashing had a huge effect. How much did it reduce the monthly proportion of deaths on average?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the mean proportion of deaths \n# before and after handwashing.\n\nmonthly_summary <- monthly %>% \n  group_by(handwashing_started) %>%\n  summarise(mean_proportion_deaths = mean(proportion_deaths))\n\n# Printing out the summary.\nmonthly_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  handwashing_started mean_proportion_deaths\n  <lgl>                                <dbl>\n1 FALSE                               0.105 \n2 TRUE                                0.0211\n```\n\n\n:::\n:::\n\n\n## 8. A statistical analysis of Semmelweis handwashing data\n\nIt reduced the proportion of deaths by around 8 percentage points! From 10% on average before handwashing to just 2% when handwashing was enforced (which is still a high number by modern standards). To get a feeling for the uncertainty around how much handwashing reduces mortalities we could look at a confidence interval (here calculated using a t-test).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating a 95% Confidence intrerval using t.test \ntest_result <- t.test( proportion_deaths ~ handwashing_started, data = monthly)\ntest_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  proportion_deaths by handwashing_started\nt = 9.6101, df = 92.435, p-value = 1.445e-15\nalternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0\n95 percent confidence interval:\n 0.06660662 0.10130659\nsample estimates:\nmean in group FALSE  mean in group TRUE \n         0.10504998          0.02109338 \n```\n\n\n:::\n:::\n\n\n## 9. The fate of Dr. Semmelweis\n\nThat the doctors didn't wash their hands increased the proportion of deaths by between 6.7 and 10 percentage points, according to a 95% confidence interval. All in all, it would seem that Semmelweis had solid evidence that handwashing was a simple but highly effective procedure that could save many lives.\n\nThe tragedy is that, despite the evidence, Semmelweis' theory — that childbed fever was caused by some \"substance\" (what we today know as *bacteria*) from autopsy room corpses — was ridiculed by contemporary scientists. The medical community largely rejected his discovery and in 1849 he was forced to leave the Vienna General Hospital for good.\n\nOne reason for this was that statistics and statistical arguments were uncommon in medical science in the 1800s. Semmelweis only published his data as long tables of raw data, but he didn't show any graphs nor confidence intervals. If he would have had access to the analysis we've just put together he might have been more successful in getting the Viennese doctors to wash their hands.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The data Semmelweis collected points to that:\ndoctors_should_wash_their_hands <- TRUE\n```\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}